{
    "name": "Electronic Device Management by Anand",
    "version": "1.0.0",
    "category": "Electronic/ElectronicManagement",
    "author": "Anand",
    "sequence": -500,
    "website": "https://www.bizzappdev.com",
    "company": "BizzAppDev",
    "summary": "Used for ElectronicManagement",
    "description": """Used for ElectronicManagement""",
    "depends": [
        "product",
        "sale_management",
        "base",
        "stock",
        "mail",
        "contacts",
        "purchase",
        "mrp"
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/access_rights.xml",
        "wizard/create_emp_view.xml",
        "data/cron_job.xml",
        "data/data_sequence.xml",
        "data/mail_template.xml",
        "data/email_template.xml",
        "views/electronic_view.xml",
        "views/employee_view.xml",
        "views/product_service_view.xml",
        "views/product_category_view.xml",
        "views/product_brand_view.xml",
        "views/inherited_views.xml",
        "views/extra_price_list.xml",
        "reports/product_service_report.xml",
        "reports/report.xml",
        "reports/employee_report.xml",
        "views/menu.xml",

    ],
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True,
}
