from . import school
from . import student
from . import teacher
from . import principal
from . import course
from . import admission
from . import transport
from . import subject
from . import result
from . import manipulation
from . import project
from . import account_move
from . import mrp_production
from . import purchase
from . import sale_order
from . import sale_order_line
from . import stock_move
from . import stock_move_line
from . import stock_picking
from . import stock_rule
from . import product
