from . import electronic
from . import employee
from . import product_brand
from . import product_template
from . import sale_order
from . import res_partner
from . import product_product
from . import sale_order_line
from . import product_service
