{
    "name": "School Management by Anand",
    "version": "1.0.0",
    "category": "School/SchoolManagement",
    "author": "Anand",
    "sequence": -500,
    "website": "https://www.bizzappdev.com",
    "company": "BizzAppDev",
    "summary": "Used for school management",
    "description": """Used for school management""",
    "depends": [
        "base",
        "mail",
        "sale",
        "mrp",
        "mrp_account",
        "account",
        "sale_project",
        "sale_purchase",
        "sale_stock",
        "stock",
        "purchase",
        "purchase_stock",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "wizard/school_wizard.xml",
        "wizard/create_school.xml",
        "wizard/update_teacher_wizard_view.xml",
        "data/data.xml",
        "data/birthday_cron.xml",
        "views/school_view.xml",
        "views/student_view.xml",
        "views/teacher_view.xml",
        "views/principal_view.xml",
        "views/course_view.xml",
        "views/menu.xml",
        "views/admission_view.xml",
        "views/transport_view.xml",
        "views/subject_view.xml",
        "views/result_view.xml",
        "views/manipulation_view.xml",
        "views/sale.xml"
    ],
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True,
}
